regions: 
        1: 
        - 2
        - 3
        - 5
        2: 
        - 0 
        - 3
        - 4
        - 5
        - 7
        3: 
        - 0 
        - 3
        - 4
        - 5
        - 7

seeds: 
        - 23

plots: 
  #percents: 
  #     - 10 
  #      - 20 
  #      - 30
  #      - 40
  #      - 80
  #      - 90
          #- 100
        
        epochs: 
        - 1
          #- 10
          #- 20
          #- 30
          #- 40 

extra:
    grand_avg: False
